Align configuration classes with Home Assistant standards
ReneNulschDE/mbapi2020 pull request #270
Opened 2024-10-11 00:33 UTC by philippwaller

This PR refines the configuration classes to better adhere to Home Assistant's coding standards and best practices.

2024-10-11 05:53 UTC, ReneNulschDE commented on custom_components/mbapi2020/switch.py
> +        translation_key="Pre-entry climate control",
Translation key does not follow the rule r"^(?!.+[_-]{2})(?![_-])[a-z0-9-_]+(?<![_-])$" . You can remove this here as the key is has the correct format.

2024-10-12 06:55 UTC, ReneNulschDE requested changes
Thx - could you check the last comments please.

2024-10-12 15:45 UTC, ReneNulschDE commented
I will implement the needed changes to get the release out. Thx!

2024-10-12 18:35 UTC, philippwaller commented
Sorry, I was an roadtrip. Are you already working on it?

2024-10-12 19:29 UTC, ReneNulschDE commented
No problem. I like your contributions and all the needed stuff is fixed. Just have a problem with the not working translation. Need to dive deeper tomorrow. Thanks again!

2024-10-13 06:27 UTC, philippwaller commented
It’s strange that the translations aren’t being applied. I tested it on Friday morning and was quite sure that at least the German translations were showing up. I looked into it again last night but couldn’t spot the issue at first glance. 🤔

2024-10-13 10:21 UTC, ReneNulschDE commented
OK - the sensor/switch title translation is not working at all. It showed the German value because your HA system language is DE. I will remove the german translation for now to make sure that the entities are created with english naming. I'll merge the PR with a few other changes and then work on the translation bug.

2024-10-13 12:05 UTC, ReneNulschDE approved these changes

2024-10-13 12:06 UTC, merged